[package]
name = "githook-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "CLI for githook git hooks"

[[bin]]
name = "githook"
path = "src/main.rs"

[dependencies]
githook.workspace = true
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
tempfile.workspace = true
dirs = "5.0"
self_update = "0.41"
serde_json = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }